"""
Django settings for backend_mastery project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta  # Needed later for JWT


load_dotenv()
# --------------------------------------------------
# BASE DIRECTORY 
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# SECURITY SETTINGS
# --------------------------------------------------

SECRET_KEY = 'django-insecure-3$tgmugo6*7bq+^4(juo+yir_ekgc@z&bqsb@^a)+)wn1r9=rc'

DEBUG = True  # ⚠ Set False in production

ALLOWED_HOSTS = []


# --------------------------------------------------
# INSTALLED APPLICATIONS
# --------------------------------------------------

INSTALLED_APPS = [
    # ---- Default Django Apps ----
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',   # Required for Session Authentication
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ---- Third Party ----
    'rest_framework',            # DRF Core

    'rest_framework_simplejwt',  # 🔒 Uncomment when using JWT
    'rest_framework_simplejwt.token_blacklist',
    # ---- Your Apps ----
    'api1_crud',
    'api2_posts',
    'api3_secure_posts',
    'exam_blog',
    'test1',
    'Gateway',
    'django_celery_results',
]


# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Needed for session auth
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attaches request.user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'backend_mastery.urls'


# --------------------------------------------------
# TEMPLATES (Used for Admin / HTML Views)
# --------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend_mastery.wsgi.application'


# --------------------------------------------------
# DATABASE
# --------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# --------------------------------------------------
# PASSWORD VALIDATORS
# (Used during user registration)
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------------------------------
# INTERNATIONALIZATION
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------------------------------------
# STATIC & MEDIA FILES
# --------------------------------------------------

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --------------------------------------------------
# DEFAULT PRIMARY KEY
# --------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==================================================
# 🔐 AUTHENTICATION CONFIGURATION SECTION
# ==================================================

# --------------------------------------------------
# 🔹 SESSION AUTHENTICATION (Current Working Mode)
# --------------------------------------------------
# Used when:
# - login(request, user)
# - Django admin login
# - DRF Browsable API login
# - Cookie-based authentication
# --------------------------------------------------

# ❌ This is currently outside REST_FRAMEWORK.
# It should normally be inside REST_FRAMEWORK.
# Kept here for learning clarity.

# DEFAULT_AUTHENTICATION_CLASSES = [
#     'rest_framework.authentication.SessionAuthentication',
#     'rest_framework.authentication.BasicAuthentication',
# ]


# --------------------------------------------------
# 🔹 JWT AUTHENTICATION (Future Mode)
# --------------------------------------------------
# Uncomment when switching to JWT.
# Then REMOVE SessionAuthentication above.
# --------------------------------------------------

REST_FRAMEWORK = {
    # "DEFAULT_AUTHENTICATION_CLASSES": (
    #     "rest_framework_simplejwt.authentication.JWTAuthentication",
    # ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "test1.authentication.CustomJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
    "rest_framework.permissions.IsAuthenticated",
)
    # "DEFAULT_PERMISSION_CLASSES": (
    #     "rest_framework.permissions.AllowAny",
    # ),
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
        # 🔥 Enable rotation
    'ROTATE_REFRESH_TOKENS': True,

    # 🔥 Blacklist old refresh tokens
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    
}


GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")


# ################# Stripe Keys #################

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

############## Celery Configuration ################
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"